[package]
name = "Shinigami"
version = "0.1.0"
authors = ["ne0ndrag0n <ne0ndrag0n@users.noreply.github.com>"]
edition = "2018"

[dependencies]
serenity = "0.5"
toml = "0.4"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
regex = "1"